### ISSUE TITLE
Provide DomArchive in CSV or JSON format

### ISSUE THREAD

**Issue by cool-RR** [DomArchive/DomArchive#3]
I haven't worked with R before, and figuring out how to use it is something I'll need to figure out before I could use DomArchive.

It would have been helpful if the data in DomArchive were available in more universal, static formats such as CSV, JSON or SQLITE.

**Comment by nusretipek** [comment]
Dear cool-RR,

Indeed can benefit from a universal statis format while most animal dominance research centered around the R programming language. I can see from your profile that Python is a strong point of you, if that's the case, I would suggest you to load the Rdata files inside the data folder (https://github.com/DomArchive/DomArchive/tree/master/data) usind Rdata package. You will get parsed data in Python and easily conver the format you would like for future analysis. See some basic code,

```
import rdata

parsed = rdata.parser.parse_file('/content/dom.metadata.RData')
converted = rdata.conversion.convert(parsed)
converted['dom.metadata']
```

```
parsed = rdata.parser.parse_file('/content/dom.data.RData')
converted = rdata.conversion.convert(parsed)
converted['dom.data']['Adcock_2015a']['matrix']
```

I hope it helps,
Nusret

**Comment by cool-RR** [comment]
Thank you! I indeed used code similar to yours to convert to CSV, graciously provided by ChatGPT :) Thanks anyway.

**Comment by straussed** [comment]
thanks @nusretipek and @cool-RR for your suggestions
